### ISSUE TITLE
Beginner question: Any examples of javascript front end interacting with para?

### ISSUE THREAD

**Issue by genloz** [Erudika/para-client-php#1]
Hi!
I've just setup scoold with a para backend, and am interested in pulling out recent posts and sharing them as a 'teaser' on another website (sharepoint). 
Do you have any examples of how to do this with a javascript front end client?
Thank you!

**Comment by albogdano** [comment]
```js
var ParaClient = require('para-client-js');
var pc = new ParaClient('ACCESS_KEY', 'SECRET_KEY');
pc.findQuery("question" "*").then(function(questionsArray) { // use data })
```
